// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7gkr_JJ51Ef7kHYzV1ktBcd2_agBeMyM',
    appId: '1:21422157365:web:458b85e82e2e7f148ccb7c',
    messagingSenderId: '21422157365',
    projectId: 'aztroboutique',
    authDomain: 'aztroboutique.firebaseapp.com',
    storageBucket: 'aztroboutique.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_K6RPHAcjNsPAKw69yosvAlNuwLXba7c',
    appId: '1:21422157365:android:0fef713f7fff59888ccb7c',
    messagingSenderId: '21422157365',
    projectId: 'aztroboutique',
    storageBucket: 'aztroboutique.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4B6FJ1qS4qLFyTccUE-kdE08SYXAeULo',
    appId: '1:21422157365:ios:fa38614ac07384fc8ccb7c',
    messagingSenderId: '21422157365',
    projectId: 'aztroboutique',
    storageBucket: 'aztroboutique.firebasestorage.app',
    iosBundleId: 'com.aztroboutique.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4B6FJ1qS4qLFyTccUE-kdE08SYXAeULo',
    appId: '1:21422157365:ios:fa38614ac07384fc8ccb7c',
    messagingSenderId: '21422157365',
    projectId: 'aztroboutique',
    storageBucket: 'aztroboutique.firebasestorage.app',
    iosBundleId: 'com.aztroboutique.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7gkr_JJ51Ef7kHYzV1ktBcd2_agBeMyM',
    appId: '1:21422157365:web:bad69941931658a78ccb7c',
    messagingSenderId: '21422157365',
    projectId: 'aztroboutique',
    authDomain: 'aztroboutique.firebaseapp.com',
    storageBucket: 'aztroboutique.firebasestorage.app',
  );
}
